/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modul_3_ObjectSerialization;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.*;
//import java.util.regex.PatternSyntaxException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableRowSorter;
import Modul_3_ObjectSerialization.PencarianMHS;
import java.util.regex.PatternSyntaxException;

public class mahasiswa extends javax.swing.JFrame {

    int b = 0;
    public int nim = 0;
    public String nama = "";
    public String asal = "";
    public String kelasPraktikum = "";
    List<Mahasiswaku> participants = new ArrayList<Mahasiswaku>();
    SerializationDemo demo = new SerializationDemo();
//    private TableRowSorter<PencarianMHS> sorter;
//    RowFilter<PencarianMHS,Object> rf = null;
    
//    private PencarianMHS tableModel = null;
//    private TableRowSorter<PencarianMHS> sorter;
//    public String firstName = "";
//    public String lastName = "";
////    private int age;
//    public int age = 0;
    public mahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ADD = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        SAVE = new javax.swing.JButton();
        SEARCH = new javax.swing.JButton();
        CARI = new javax.swing.JTextField();
        UPDATE = new javax.swing.JButton();
        PRINT = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DATA MAHASISWA");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "NAMA", "ASAL", "KELAS PRAKTIKUM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        ADD.setText("ADD");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });

        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });

        SEARCH.setText("SEARCH");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });

        UPDATE.setText("UPDATE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });

        PRINT.setText("PRINT");
        PRINT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRINTActionPerformed(evt);
            }
        });

        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EXIT)
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(UPDATE)
                                .addGap(18, 18, 18)
                                .addComponent(DELETE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SAVE)
                                .addGap(18, 18, 18)
                                .addComponent(PRINT))
                            .addComponent(CARI, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EXIT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SEARCH)
                    .addComponent(CARI, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADD)
                    .addComponent(DELETE)
                    .addComponent(SAVE)
                    .addComponent(UPDATE)
                    .addComponent(PRINT))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        // TODO add your handling code here:
        b = Integer.parseInt(JOptionPane.showInputDialog("Jumlah Mahasiswa"));
        
        for (int i = 0; i < b; i++) {
            
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//            firstName = JOptionPane.showInputDialog("Input First Name");
//            lastName = JOptionPane.showInputDialog("Input Last Name");
//            age = Integer.parseInt((JOptionPane.showInputDialog("Input Age")));
            nim = Integer.parseInt((JOptionPane.showInputDialog("NIM")));
            nama = JOptionPane.showInputDialog("Nama");
            asal = JOptionPane.showInputDialog("Asal");
            kelasPraktikum = JOptionPane.showInputDialog("Kelas Praktikum");
            
            model.addRow(new Object[]{
//            jTable1.getRowCount()+1, firstName, lastName, age
            nim, nama, asal, kelasPraktikum
                    
        });
//           jTable1.addMouseListener(new MouseAdapter() {
//            public void mousePressed(MouseEvent me) {
//                int selRow = jTable1.getSelectedRow();
//                int selCol = jTable1.getSelectedColumn();
//                Object value = jTable1.getValueAt(selRow, selCol);
//                System.out.println(value.toString());
//                
//             }
//            
//          });
           participants.add(new Mahasiswaku(nim, nama, asal, kelasPraktikum));
        }
        
       
    }//GEN-LAST:event_ADDActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int baris = jTable1.getRowCount();
        int row = jTable1.getSelectedRow();
        if(row>=0){
            int ok = JOptionPane.showConfirmDialog(null, "Yakin Mau Hapus ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
            if (ok==0) {
                model.removeRow(row);
                participants.remove(row);
                
            }
        }else {
            for (int i = 0; i < baris; i++) {
                model.removeRow(0);
                participants.remove(0);
                
            }
        }
//        
    }//GEN-LAST:event_DELETEActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        // TODO add your handling code here:
       
        demo.serialize(participants, "E:/bismillah smt 5/IP_search/Mahasiswa.ser");

        JOptionPane.showMessageDialog(null, "Serialize is done\n");
    }//GEN-LAST:event_SAVEActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
        // TODO add your handling code here:
//        PencarianMHS pms = new PencarianMHS();
//
//        try {
//            rf = RowFilter.regexFilter("(?i)^"+CARI.getText(), 0,1,2,3);
//        } catch (PatternSyntaxException e) {
//            System.out.println(e.getMessage());
//        }
//        sorter.setRowFilter(rf);
//        if (CARI.getText()== jTable1.getColumnName(NORMAL)) {
//            
//        } else {
//        }
    }//GEN-LAST:event_SEARCHActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        // TODO add your handling code here:
       //  demo.seri(participants, "E:/bismillah smt 5/IP_search/Mahasiswa.ser");
        // JOptionPane.showMessageDialog(null, "UPDATE\n");
        nim = Integer.parseInt((JOptionPane.showInputDialog("NIM")));
        nama = JOptionPane.showInputDialog("Nama");
        asal = JOptionPane.showInputDialog("Asal");
        kelasPraktikum = JOptionPane.showInputDialog("Kelas Praktikum");
    }//GEN-LAST:event_UPDATEActionPerformed

    private void PRINTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRINTActionPerformed
        // TODO add your handling code here:
        List<Mahasiswaku> newList = demo.deserialize("E:/bismillah smt 5/IP_search/Mahasiswa.ser");
        JOptionPane.showMessageDialog(null, "New List : " + newList);
    }//GEN-LAST:event_PRINTActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JTextField CARI;
    private javax.swing.JButton DELETE;
    private javax.swing.JButton EXIT;
    private javax.swing.JButton PRINT;
    private javax.swing.JButton SAVE;
    private javax.swing.JButton SEARCH;
    private javax.swing.JButton UPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
